#!/bin/sh
BASE_IMAGE_BUILD=golang:alpine
BASE_IMAGE_RELEASE=alpine:latest

docker pull ${BASE_IMAGE_BUILD} ${BASE_IMAGE_RELEASE}
DOCKER_BUILDKIT=1 docker build --build-arg BASE_IMAGE_BUILD=${BASE_IMAGE_BUILD} --build-arg BASE_IMAGE_RELEASE=${BASE_IMAGE_RELEASE} -t jdschulze/restinthemiddle:latest .
